import { db, handleFirestoreError, OperationType } from '../firebase';
import { collection, getDocs, setDoc, doc, query, where } from 'firebase/firestore';

export interface NoRekMapping {
  keterangan: string;
  namaCabang: string;
}

const NOREK_DATA = `AMBON 1,CP AMBON
ANTANG KCA,CP ANTANG
PEGADAIAN BANGKALA,CP BANGKALA
PEGADAIAN UPC TAMANROYA,UPC TAMANROYA
BANTAENG 1,CP BANTAENG
BARRU 1,CP BARRU
BAU-BAU 1,CP BAUBAU
PGD UPC EREKE,UPC EREKE
PEGADAIAN CP BELOPA,CP BELOPA
PGD UPC KEERA,UPC KEERA
UPC LAROMPONG,UPC LAROMPONG
UPC PADANG SAPPA,UPC PADANG SAPPA
UPC SULI,UPC SULI
BONTOALA 1,CP BONTOALA
PEGADAIAN BONTOBAHARI,CP BONTOBAHARI
BULUKUMBA 1,CP BULUKUMBA
UPC TANETE,UPC TANETE
CA'BENGE KCA,CP CABENGE
DAYA KCA,CP DAYA
HERTASNING 1,CP HERTASNING
JENEPONTO KCA,CP JENEPONTO
PGD UPC TOLO,UPC TOLO
KENDARI 1,CP KENDARI
UPC WANCI,UPC WANCI
UPC WAWONII,UPC WAWONII
KOLAKA 1,CP KOLAKA
LIMBUNG 1,CP LIMBUNG
MAJENE KCA,CP MAJENE
MAKASSAR 1,CP MAKASSAR
MALILI KCA,CP MALILI
UPC TOMONI,UPC TOMONI
UPC WOWONDULA,UPC WOWONDULA
MALIMONGAN BARU 1,CP MALIMONGAN BARU
MAMUJU 1,CP MAMUJU
UPC PASAR TAPALANG,UPC PASAR TAPALANG
UPC PASAR TASIU,UPC PASAR TASIU
UPC TIKKE,UPC TIKKE
MANDONGA 1,CP MANDONGA
MARISO 1,CP MARISO
MAROS 1,CP MAROS
MASAMBA KCA,CP MASAMBA
MASONI KCA,CP MASOHI
NUSANIWE KCA,CP NUSANIWE
PA'BAENG-BAENG 1,CP PABAENGBAENG
PALANGGA 1,CP PALLANGGA
PALOPO SUP,CP PALOPO
PEGADAIAN PANAKUKANG,CP PANAKKUKANG
PANGKEP 1,CP PANGKEP
PARANGTAMBUNG 1,CP PARANGTAMBUNG
PARE-PARE 1,CP PARE PARE
PEGADAIAN PASAR BUTUNG,CP PASAR BUTUNG
PGD CP PASAR BUTUNG,CP PASAR BUTUNG
PASAR MINI S 1,CP PASAR MINI
UPC PASAR DOPING,UPC PASAR DOPING
UPC SABANG BARU,UPC SABANG PARU
PASAR SENTRAL PALOPO,CP PASAR SENTRAL PALOPO
PASSO KCA,CP PASSO
PELITA 1,CP PELITA
PINRANG 1,CP PINRANG
POLEWALI 1,CP POLEWALI
UPC MAMASA,UPC MAMASA
PEGADAIAN POMALA,CP POMALAA
UPC BOEPINANG,UPC BOEPINANG
RAHA 1,CP RAHA
UPC TONGKUNA,UPC TONGKUNA
RANTEPAO 1,CP RANTEPAO
PEGADAIAN CP RAPPANG,CP RAPPANG
SELAYAR 1,CP SELAYAR
SENGKANG 1,CP SENGKANG
SIDRAP 1,CP SIDRAP
SINJAI 1,CP SINJAI
SUNGGUMINASA KCA,CP SUNGGUMINASA
PEGADAIAN CP TAKALAR,CP TAKALAR
TALASALAPANG 1,CP TALASALAPANG
PGD CP TAMALANREA,CP TAMALANREA
TUAL 1,CP TUAL
UNAAHA RAPPANG 1,CP UNAAHA
PGD UPC LADONGI,UPC LADONGI
VETERAN 1,CP VETERAN
WATANPONE 1,CP WATAMPONE
PGD UPC AJANGALE,UPC AJANGALE
UPC MARE KCA,UPC MARE
UPC ULOE KCA,UPC ULOE
WATANSOPPENG KCA,CP WATANSOPPENG
UPC BATU BATU,UPC BATU BATU
UPC LAPPARIAJA,UPC LAPPARIAJA
UPC PANINCONG,UPC PANINCONG
PGD UPC TAJUNCU,UPC TAJUNCU
UPC TAKALALA,UPC TAKALALA
PGD CP WONOMULYO,CP WONOMULYO
WUA WUA 1,CP WUA WUA
PGD UPC WANGI-WANGI,UPC WANGI-WANGI
PGD UPC WOTU,UPC WOTU
PEGADAIAN UPC BONE BONE,UPC BONEBONE
PEGADAIAN UPC SUKAMAJU,UPC SUKAMAJU
PEGADAIAN UPC BELAWA BARU,UPC BRI BELAWA BARU
PEG SYA KENDARI,CPS KENDARI
PEG SYA PANGKAJENE,CPS PANGKAJENE
PEGADAIAN UPS JAMPUE,UPS JAMPUE
PEGADAIAN UPS AHMAD YANI,UPS AHMAD YANI
PEGADAIAN UPS KEMAKMURAN,UPS KEMAKMURAN
UPS PSR STRL PINRANG,UPS PSR STRL PINRANG
PEGADAIAN UPS TARAILU,UPS TARAILU
PEGADAIAN UPS WATANG SAWITO,UPS WATANG SAWITO
PEGADAIAN PANGKEP,CPS PANGKEP
UPS CEMPAE,UPS CEMPAE
PEG SYA UJUNG BULU,CPS UJUNG BULU
PEGADAIAN UPS BONE,UPS BONE
PEGADAIAN UPS P BARU BANTAENG,UPS P BARU BANTAENG
PGD UPS PUNGGALUKU,UPS PUNGGALUKU
7002380115,CPS CENTRAL
7100926037,CPS HASANUDDIN
7058988426,CPS AMBON
7023495516,CPS KENDARI
1033427863,CPS UJUNG BULU
PT PEGADAIAN (PERSERO) SYARIAH PANGKEP,CPS PANGKEP
PERUM PEGADAIAN CABANG PAREPARE,CP PARE PARE
PEGADAIAN CABANG AMBON,CP AMBON
PEGADAIAN CABANG ANTANG,CP ANTANG
PEGADAIAN CABANG PELITA,CP PELITA
PEGADAIAN CABANG BANTAENG,CP BANTAENG
PEGADAIAN CABANG BONTOALA,CP BONTOALA
PEGADAIAN CABANG BARRU,CP BARRU
PT PEGADAIAN (PERSERO) CABANG BAUBAU,CP BAUBAU
PEGADAIAN CABANG WATAMPONE,CP WATAMPONE
PEGADAIAN CABANG BULUKUMBA,CP BULUKUMBA
PEGADAIAN CABANG PARANGTAMBUNG,CP PARANGTAMBUNG
PEGADAIAN CABANG LIMBUNG,CP LIMBUNG
PEGADAIAN CABANG PALANGGA,CP PALLANGGA
PEGADAIAN CABANG KENDARI,CP KENDARI
PEGADAIAN CABANG KOLAKA,CP KOLAKA
PEGADAIAN CABANG WUA - WUA,CP WUA WUA
PEGADAIAN CABANG MAJENE,CP MAJENE
PEGADAIAN CABANG MAKASSAR,CP MAKASSAR
PEGADAIAN CABANG MALILI,CP MALILI
PEGADAIAN CABANG MAMUJU,CP MAMUJU
PEGADAIAN CABANG MANDONGA,CP MANDONGA
PEGADAIAN CABANG MAROS,CP MAROS
PEGADAIAN CABANG MASAMBA,CP MASAMBA
PEGADAIAN CABANG MASOHI,CP MASOHI
PEGADAIAN CABANG MARISO,CP MARISO
PEGADAIAN CABANG PALOPO,CP PALOPO
PEGADAIAN CABANG HERTASNING,CP HERTASNING
PEGADAIAN CABANG PANGKEP,CP PANGKEP
PEGADAIAN CABANG PS. BUTUNG,CP PASAR BUTUNG
PEGADAIAN CABANG PS SENTRAL PALOPO,CP PASAR SENTRAL PALOPO
PEGADAIAN CABANG PASSO,CP PASSO
PEGADAIAN CABANG PABAENG - BAENG,CP PABAENGBAENG
PEGADAIAN CABANG TALASALAPANG,CP TALASALAPANG
PEGADAIAN CABANG PINRANG,CP PINRANG
PEGADAIAN CABANG POLEWALI,CP POLEWALI
PEGADAIAN CABANG MALIMONGAN BARU,CP MALIMONGAN BARU
PEGADAIAN CABANG DAYA,CP DAYA
PEGADAIAN CABANG RAHA,CP RAHA
PEGADAIAN CABANG SENGKANG,CP SENGKANG
PEGADAIAN CABANG PS.MINI,CP PASAR MINI
PEGADAIAN CABANG SIDRAP,CP SIDRAP
PEGADAIAN CABANG SINJAI,CP SINJAI
PEGADAIAN CABANG CABENGE,CP CABENGE
PEGADAIAN CABANG SUNGGUMINASA,CP SUNGGUMINASA
PEGADAIAN CABANG TAKALAR,CP TAKALAR
PEGADAIAN CABANG RANTEPAO,CP RANTEPAO
PEGADAIAN CABANG TUAL,CP TUAL
PEGADAIAN CABANG UNAHA,CP UNAAHA
PEGADAIAN CABANG VETERAN,CP VETERAN
PEGADAIAN CABANG NUSANIWE,CP NUSANIWE
PEGADAIAN CABANG WATANSOPPENG,CP WATANSOPPENG
PEGADAIAN CABANG WONOMULYO,CP WONOMULYO
PEGADAIAN CABANG SUDIANG PT,CP SUDIANG
PEGADAIAN (PERSERO) UNIT SYARIAH PALOPO PT,CPS L U W U
PEGADAIAN CABANG POMALAA PT,CP POMALAA
PERUM PEGADAIAN TAMALANREA,CP TAMALANREA
PEGADAIAN CABANG KEPULAUAN SELAYAR PT,CP SELAYAR
PEGADAIAN PANAKKUKANG,CP PANAKKUKANG
PERUM PEGADAIAN DUA PITUE,CP DUA PITUE
PEGADAIAN CABANG RAP,CP RAPPANG
PT PEGADAIAN (PERSERO) CABANG BELOPA BUMN,CP BELOPA
PEGADAIAN CAB. JENEPONTO, PERUM,CP JENEPONTO`;

export const norekService = {
  async getAll(): Promise<NoRekMapping[]> {
    const path = 'norek_mapping';
    try {
      const snapshot = await getDocs(collection(db, path));
      
      // Check if we need to seed (either empty or missing new mappings)
      const hasNewMappings = snapshot.docs.some(doc => doc.id.includes('JENEPONTO'));
      
      if (snapshot.empty || !hasNewMappings) {
        try {
          console.log('Seeding/Updating norek mappings...');
          await this.seed();
          // Fetch again after seeding
          const updatedSnapshot = await getDocs(collection(db, path));
          return updatedSnapshot.docs.map(doc => doc.data() as NoRekMapping);
        } catch (seedError) {
          console.warn('Failed to seed norek_mapping data (likely guest user), falling back to local data:', seedError);
          if (!snapshot.empty) {
            return snapshot.docs.map(doc => doc.data() as NoRekMapping);
          }
          // Parse local data as fallback
          return NOREK_DATA.split('\n').map(line => {
            const [keterangan, namaCabang] = line.split(',');
            return { keterangan, namaCabang };
          }).filter(item => item.keterangan && item.namaCabang);
        }
      }
      return snapshot.docs.map(doc => doc.data() as NoRekMapping);
    } catch (error) {
      console.error('Error fetching norek_mapping data:', error);
      // Fallback to local data on any error
      return NOREK_DATA.split('\n').map(line => {
        const [keterangan, namaCabang] = line.split(',');
        return { keterangan, namaCabang };
      }).filter(item => item.keterangan && item.namaCabang);
    }
  },

  async seed() {
    const lines = NOREK_DATA.split('\n');
    for (const line of lines) {
      const [keterangan, namaCabang] = line.split(',');
      if (keterangan && namaCabang) {
        const id = keterangan.replace(/[^a-zA-Z0-9]/g, '_');
        await setDoc(doc(db, 'norek_mapping', id), { keterangan, namaCabang });
      }
    }
  }
};
